version: '3.8'

services:
  agentsworkflow:
    build: .
    container_name: website
    restart: always
    ports:
      - "821:821"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  # <-- Acesso ao Docker
    command: > 
      sh -c "python LocalRun.py"
    mem_limit: 500MB
    cpus: "1.5"
    networks:
      - rede_externa


networks:
  rede_externa:
    external: true
